In [43]:
#성범죄자 알림이 지역별 통계 openApi URL 파싱 후 판다스 데이터프레임에 저장

import pandas as pd
# from bs4 import BeautifulSoup
import xml.etree.ElementTree as ET
# import sys
import urllib.request, re
import requests

url='http://116.67.77.182/openapi/SOCitysStats/'

response = requests.get(url)
html = response.text

print(html)

# soup = BeautifulSoup(html, 'html.parser')

# result = re.findall(r'<Result>.+?</Result>', html, re.DOTALL)

data = re.findall(r'<City>.+?</City>', html, re.DOTALL)

print(type(data))

cnt=1

rows=[]

for i in data:
    cityname = re.search(r'<city-name>(.+)</city-name>', i)
    citycount = re.search(r'<city-count>(.+)</city-count>', i)
    print(cnt, cityname, citycount)
    rows.append({
               "cityname":cityname.group(1),
               "citycount":citycount.group(1)})
    cnt = cnt +1

# convert XML data to pandas DataFrame
columns = ["cityname","citycount"]
df = pd.DataFrame(rows,columns = columns )
df

<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Result><Code>00</Code><City><city-name>강원도</city-name><city-count>133</city-count></City><City><city-name>경기도</city-name><city-count>876</city-count></City><City><city-name>경상남도</city-name><city-count>282</city-count></City><City><city-name>경상북도</city-name><city-count>235</city-count></City><City><city-name>광주광역시</city-name><city-count>122</city-count></City><City><city-name>대구광역시</city-name><city-count>193</city-count></City><City><city-name>대전광역시</city-name><city-count>105</city-count></City><City><city-name>부산광역시</city-name><city-count>217</city-count></City><City><city-name>서울특별시</city-name><city-count>556</city-count></City><City><city-name>세종특별자치시</city-name><city-count>9</city-count></City><City><city-name>울산광역시</city-name><city-count>79</city-count></City><City><city-name>인천광역시</city-name><city-count>228</city-count></City><City><city-name>전라남도</city-name><city-count>187</city-count></City><City><city-name>전라북도</city-name><city-count>186</city-count></City><City><city-name>제주특별자치도</city-name><city-count>50</city-count></City><City><city-name>충청남도</city-name><city-count>197</city-count></City><City><city-name>충청북도</city-name><city-count>126</city-count></City></Result>
<class 'list'>
1 <_sre.SRE_Match object; span=(6, 32), match='<city-name>강원도</city-name>'> <_sre.SRE_Match object; span=(32, 60), match='<city-count>133</city-count>'>
2 <_sre.SRE_Match object; span=(6, 32), match='<city-name>경기도</city-name>'> <_sre.SRE_Match object; span=(32, 60), match='<city-count>876</city-count>'>
3 <_sre.SRE_Match object; span=(6, 33), match='<city-name>경상남도</city-name>'> <_sre.SRE_Match object; span=(33, 61), match='<city-count>282</city-count>'>
4 <_sre.SRE_Match object; span=(6, 33), match='<city-name>경상북도</city-name>'> <_sre.SRE_Match object; span=(33, 61), match='<city-count>235</city-count>'>
5 <_sre.SRE_Match object; span=(6, 34), match='<city-name>광주광역시</city-name>'> <_sre.SRE_Match object; span=(34, 62), match='<city-count>122</city-count>'>
6 <_sre.SRE_Match object; span=(6, 34), match='<city-name>대구광역시</city-name>'> <_sre.SRE_Match object; span=(34, 62), match='<city-count>193</city-count>'>
7 <_sre.SRE_Match object; span=(6, 34), match='<city-name>대전광역시</city-name>'> <_sre.SRE_Match object; span=(34, 62), match='<city-count>105</city-count>'>
8 <_sre.SRE_Match object; span=(6, 34), match='<city-name>부산광역시</city-name>'> <_sre.SRE_Match object; span=(34, 62), match='<city-count>217</city-count>'>
9 <_sre.SRE_Match object; span=(6, 34), match='<city-name>서울특별시</city-name>'> <_sre.SRE_Match object; span=(34, 62), match='<city-count>556</city-count>'>
10 <_sre.SRE_Match object; span=(6, 36), match='<city-name>세종특별자치시</city-name>'> <_sre.SRE_Match object; span=(36, 62), match='<city-count>9</city-count>'>
11 <_sre.SRE_Match object; span=(6, 34), match='<city-name>울산광역시</city-name>'> <_sre.SRE_Match object; span=(34, 61), match='<city-count>79</city-count>'>
12 <_sre.SRE_Match object; span=(6, 34), match='<city-name>인천광역시</city-name>'> <_sre.SRE_Match object; span=(34, 62), match='<city-count>228</city-count>'>
13 <_sre.SRE_Match object; span=(6, 33), match='<city-name>전라남도</city-name>'> <_sre.SRE_Match object; span=(33, 61), match='<city-count>187</city-count>'>
14 <_sre.SRE_Match object; span=(6, 33), match='<city-name>전라북도</city-name>'> <_sre.SRE_Match object; span=(33, 61), match='<city-count>186</city-count>'>
15 <_sre.SRE_Match object; span=(6, 36), match='<city-name>제주특별자치도</city-name>'> <_sre.SRE_Match object; span=(36, 63), match='<city-count>50</city-count>'>
16 <_sre.SRE_Match object; span=(6, 33), match='<city-name>충청남도</city-name>'> <_sre.SRE_Match object; span=(33, 61), match='<city-count>197</city-count>'>
17 <_sre.SRE_Match object; span=(6, 33), match='<city-name>충청북도</city-name>'> <_sre.SRE_Match object; span=(33, 61), match='<city-count>126</city-count>'>

   cityname citycount
0       강원도       133
1       경기도       876
2      경상남도       282
3      경상북도       235
4     광주광역시       122
5     대구광역시       193
6     대전광역시       105
7     부산광역시       217
8     서울특별시       556
9   세종특별자치시         9
10    울산광역시        79
11    인천광역시       228
12     전라남도       187
13     전라북도       186
14  제주특별자치도        50
15     충청남도       197
16     충청북도       126